--- 
# This is sample.yml file and execute the
# commands ansible --version, hostname, and hostname -I on the instance.
# The host1 is group of hosts (group of IPs, hostnames) which is specified in the hosts file in the task folder
- hosts: host1
  tasks:
    - name: Example-1 Print Message
      debug:
             # Print the following message.
              msg: "This is print message."

    - name: Example-2 Ansible Version
      # The following command gets ansible version and store in the variable called "ansibleversion."
      command: "ansible --version"
      register: ansibleversion

    - debug:
            # Print the variable "ansibleversion" value. This value is an ansible version.
            msg: "Ansible Version: {{ ansibleversion.stdout }}"

    - name: Example-3 Hostname
      # The following command gets the hostname of the instance and store in the variable called "currenthostname."
      command: "hostname"
      register: currenthostname

    - debug:
            # Print the variable "currenthostname" value. This value is the hostname of the instance.
            msg: "The hostname: {{ currenthostname.stdout }}"

    - name: Example-4 Host IP
      # The following command gets IP of the instance and store in the variable called "hostIP."
      command: "hostname -I"
      register: hostIP

    - debug:
            # Print the variable "hostIP" value. This value is the host IP of the instance.
            msg: "The host IP: {{ hostIP.stdout }}"

